---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-auth-config
  namespace: jinkit-ops
  labels:
    telco.ocp.run/deployment: powerdns
    telco.ocp.run/app: powerdns-auth
data:
  pdns.conf: |
    launch=gmysql
    gmysql-host=
    gmysql-host=pdns-mariadb
    gmysql-user=pdns
    gmysql-dbname=pdns
    gmysql-port=3306
    gmysql-password=pdnspassword

    webserver=yes
    webserver=yes
    webserver-address=0.0.0.0
    webserver-allow-from=0.0.0.0/0
    webserver-port=8081
    webserver-password=secret

    api=yes
    api-key=skywalker