---
apiVersion: v1
kind: Service
metadata:
  name: pdns-auth-udp
  namespace: jinkit-ops
  labels:
    telco.ocp.run/deployment: powerdns
    telco.ocp.run/service: powerdns-auth-dns
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: ippool-roderika-01
    metallb.universe.tf/loadBalancerIPs: 10.50.1.5
spec:
  selector:
    app: pdns-auth
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true