---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-rec-config
  namespace: powerdns
data:
  pdns.conf: |
    allow-from=0.0.0.0/0
    local-port=53
    webserver=yes
    webserver-allow-from=0.0.0.0/0
    webserver-port=8082
    webserver-password=secret
    api-key=secret
    webserver-address=0.0.0.0
    system-resolver-ttl=60
    max-negative-ttl=1
    forward-zones-recurse=nekohouse.ca=pdns-auth-udp,.=1.1.1.1:53