---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor
  namespace: powerdns
    app: pdns-recursor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-recursor
  template:
    metadata:
      labels:
        app: pdns-recursor
    spec:
      serviceAccountName: pdns
      containers:
      - name: pdns-recursor
        image: powerdns/pdns-recursor-51:5.1.3
        ports:
        # Maybe use this at a later time for transfers, but not needed for basic functionality.
        # - containerPort: 53
        #   protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 8082
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
        volumeMounts:
        - name: pdns-rec-config-volume
          mountPath: /etc/powerdns/recursor.d/pdns.conf
          subPath: pdns.conf
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      volumes:
      - name: pdns-rec-config-volume
        configMap:
          name: pdns-rec-config