---
apiVersion: v1
kind: Service
metadata:
  name: pdns-rec-udp
  namespace: jinkit-ops
  labels:
    telco.ocp.run/deployment: powerdns
    telco.ocp.run/service: powerdns-rec-dns
spec:
  selector:
    app: pdns-recursor
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53