---
apiVersion: v1
kind: Service
metadata:
  name: pdns-rec-api
  namespace: jinkit-ops
  labels:
    telco.ocp.run/deployment: powerdns
    telco.ocp.run/service: powerdns-rec-api
spec:
  selector:
    app: pdns-recursor
  ports:
  - protocol: TCP
    port: 8082