---
apiVersion: v1
kind: Secret
metadata:
  name: pdns-secrets
  namespace: jinkit-ops
  labels:
    k8s.mariadb.com/watch:
    telco.ocp.run/deployment: powerdns
    telco.ocp.run/app: powerdns-db
stringData:
  MARIADB_PASSWORD: pdnspassword
  MARIADB_ROOT_PASSWORD: verysecret