---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: 
  name: pdns-secrets
  namespace: powerdns
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: MARIADB_PASSWORD
      metadataPolicy: None
    secretKey: MARIADB_PASSWORD
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: MARIADB_ROOT_PASSWORD
      metadataPolicy: None
    secretKey: MARIADB_ROOT_PASSWORD
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pdns-secret