---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
  namespace: powerdns
  labels:
    app: powerdns
    dc: ocp-centralis
spec:
  rootPasswordSecretKeyRef:
    name: pdns-secret
    key: MARIADB_ROOT_PASSWORD
  storage:
    size: 5Gi
    storageClassName: nfs-csi
  service:
    type: ClusterIP
  