---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nekohouse
  namespace: powerdns
  labels:
    app: powerdns
    dc: ocp-centralis
spec:
  mariaDbRef:
    name: mariadb
    namespace: powerdns