---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: pdns
  namespace: jinkit-ops
  labels:
    telco.ocp.run/deployment: powerdns
    telco.ocp.run/app: powerdns-db
spec:
  mariaDbRef:
    name: pdns-mariadb
  passwordSecretKeyRef:
    name: pdns-secrets
    key: MARIADB_PASSWORD
  maxUserConnections: 0