---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: pdns
  namespace: powerdns
  labels:
    app: powerdns
    dc: ocp-centralis
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: pdns-secrets
    key: MARIADB_PASSWORD
  maxUserConnections: 0